"""empty message

Revision ID: 130e5a98fc62
Revises: db97ecac1af7
Create Date: 2024-02-11 11:36:50.469310

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "130e5a98fc62"
down_revision: Union[str, None] = "db97ecac1af7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("attachment", sa.PickleType(), nullable=True),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_message",
        sa.Column("student_groups_id", sa.Integer(), nullable=False),
        sa.Column("messages_id", sa.Integer(), nullable=False),
        sa.Column("received", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["messages_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_groups_id"],
            ["student_groups.id"],
        ),
        sa.PrimaryKeyConstraint("student_groups_id", "messages_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_message")
    op.drop_table("messages")
    # ### end Alembic commands ###
