"""empty message

Revision ID: 199391c6467e
Revises: 
Create Date: 2024-01-18 15:33:05.292304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199391c6467e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table',
    sa.Column('student_groups_id', sa.Integer(), nullable=False),
    sa.Column('messages_id', sa.Integer(), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['student_groups_id'], ['student_groups.id'], ),
    sa.PrimaryKeyConstraint('student_groups_id', 'messages_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('student_groups')
    op.drop_table('messages')
    # ### end Alembic commands ###
