"""empty message

Revision ID: 22dde207c976
Revises: ee637d528f00
Create Date: 2024-02-05 13:32:54.839874

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "22dde207c976"
down_revision: Union[str, None] = "ee637d528f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
