"""empty message

Revision ID: de5956c4589a
Revises: 
Create Date: 2024-02-02 11:38:06.492367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5956c4589a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

faculties =  [
        "РТС",
        "ИКСС",
        "ИСиТ",
        "ФФП",
        "ЦЭУБИ",
        "СЦТ",
        "ИНО",
        "ИМ",
        "СПБКТ",
        "ВУЦ",
    ]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True, server_default="1"),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    for faculty in faculties:
        op.execute(sa.text(f"INSERT INTO faculty (name) VALUES ('{faculty}')"))
 
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('attachment', sa.PickleType(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_message',
    sa.Column('student_groups_id', sa.Integer(), nullable=False),
    sa.Column('messages_id', sa.Integer(), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['student_groups_id'], ['student_groups.id'], ),
    sa.PrimaryKeyConstraint('student_groups_id', 'messages_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_message')
    op.drop_table('messages')
    op.drop_table('admins')
    op.drop_table('student_groups')
    op.drop_table('faculty')
    # ### end Alembic commands ###
